prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: tls-prometheus
        hosts:
          - prometheus.os.cf01.eu
    hosts:
      - prometheus.os.cf01.eu # --- PROMETHEUS DOMAIN ---
    paths:
      - /

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: tls-grafana
        hosts:
          - grafana.os.cf01.eu

    hosts:
      - grafana.os.cf01.eu # --- GRAFANA DOMAIN ---
    paths:
      - /

alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: tls-alertmanager
        hosts:
          - alertmanager.os.cf01.eu

    hosts:
      - alertmanager.os.cf01.eu # --- ALERTMANAGER DOMAIN ---
    paths:
      - /
